#%RAML 0.8
---
title: Test API
baseUri: http://example.com
version: 42
/foo:
  get:
  post:
  /foo1:
    post:
      body:
        application/json:
          schema: |
            {
                "type": "object",
                "properties": {
                    "foo": {
                        "type": "string",
                        "required": true
                    },
                    "bar": {
                        "type": "string",
                        "required": false
                    }
                }
            }
          example: |
            {
                "foo": "xxx",
                "bar": "yyy"
            }
      responses:
        200:
          body:
            application/json:
    delete:
      description: delete foo1
  /foo2:
    get:
      description: get foo2
      queryParameters:
        filter:
          displayName: foo2 filter
          type: string
          description: value to filter by
          example: xxx
          required: false
/bar:
  post:
    description: create bar
/baz:
  put:
